# This is a basic workflow to help you get started with Actions
name: 'Linux Build'

# Controls when the action will run.
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        node-version: [ 18.x, 20.x ]

    # The type of runner that the job will run on
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v4

      - name: Cache Node Modules
        uses: actions/cache@v3
        with:
          # npm cache files are stored in `~/.npm` on Linux/macOS
          path: ~/.npm
          key: ${{ runner.os }}-node_modules-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node_modules

      - name: Install Required Packages
        run: |
          sudo apt-get update
          sudo apt-get install -y libgtk-3-dev libwebkit2gtk-4.0-dev libappindicator3-dev librsvg2-dev patchelf

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable

      - name: Cache Rust Project
        uses: Swatinem/rust-cache@v2
        with:
          prefix-key: ${{ runner.os }}-rust
          workspaces: src-tauri

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install NPM Dependencies
        run: npm ci

      - name: Check lint
        run: npm run ng lint

      - name: Build the app
        run: npm run build -- --features=vendored-openssl
